### ISSUE TITLE
Error in postman collection

### ISSUE THREAD

**Issue by diegoocampoh** [udacity/nd035-c3-data-stores-and-persistence-project-starter#6]
The request to create a schedule is exactly the same as the one that modifies the availability of an employee:

PUT http://localhost:8082/user/employee/1 

<img width="666" alt="Screen Shot 2021-07-06 at 9 48 09 pm" src="https://user-images.githubusercontent.com/8323577/124595041-db95df80-dea3-11eb-9142-2e3eb321be55.png">

https://github.com/udacity/nd035-c3-data-stores-and-persistence-project-starter/blob/master/starter/critter/src/main/resources/Udacity.postman_collection.json#L116-L152

Create schedule request:

<img width="664" alt="Screen Shot 2021-07-06 at 9 48 39 pm" src="https://user-images.githubusercontent.com/8323577/124595081-ee101900-dea3-11eb-9e44-b90a0573fd6d.png">

https://github.com/udacity/nd035-c3-data-stores-and-persistence-project-starter/blob/master/starter/critter/src/main/resources/Udacity.postman_collection.json#L193-L229

**Comment by UAnjali** [comment]
Hi,
Are you still facing this issue? We suggest you refer to the Knowledge hub and reach out to your assigned mentor for user-specific issues. 
Thanks
